name: general_algorithms_env
channels:
  - conda-forge
  - defaults
dependencies:
  - autopep8>=1.5.4
  - black>=20.8b1
  - flake8>=3.8.4
  - jedi>=0.17.2
  - numpy>=1.19.2
  - pytest>=6.1.2
  - pytest-cov>=2.10.1
  - python>=3.7.8
  - rope>=0.18.0
  - yapf>=0.30.0
  - scipy>=1.6.3
  - numba>=0.53.1
